name: Build Dalamud
on: [push, pull_request, workflow_dispatch]
concurrency:
  group: build_dalamud_${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - name: Checkout Dalamud
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'

          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - name: Build Dalamud
        run: .\build.ps1 compile
      - name: Test Dalamud
        run: .\build.ps1 test
      - name: Create hashlist
        run: .\CreateHashList.ps1 .\bin\Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dalamud-artifact
          path: bin\Release
          
